// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortraMeta.Data;

#nullable disable

namespace PortraMeta.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260331232030_AddFileModifiedAt")]
    partial class AddFileModifiedAt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("PortraMeta.Data.Entities.Actor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Aliases")
                        .HasColumnType("TEXT");

                    b.Property<string>("AvatarPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Actors");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.ExcludedFolder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId", "Path")
                        .IsUnique();

                    b.ToTable("ExcludedFolders");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.Library", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.Studio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("LogoPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Studios");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.VideoActor", b =>
                {
                    b.Property<int>("VideoFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ActorId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Order")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Role")
                        .HasColumnType("TEXT");

                    b.HasKey("VideoFileId", "ActorId");

                    b.HasIndex("ActorId");

                    b.ToTable("VideoActors");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.VideoFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FileModifiedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FileSizeBytes")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasFanart")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasNfo")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("HasPoster")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LibraryId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("NfoUpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalTitle")
                        .HasColumnType("TEXT");

                    b.Property<string>("Plot")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("StudioId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Year")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("LibraryId");

                    b.HasIndex("StudioId");

                    b.ToTable("VideoFiles");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.ExcludedFolder", b =>
                {
                    b.HasOne("PortraMeta.Data.Entities.Library", "Library")
                        .WithMany()
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.VideoActor", b =>
                {
                    b.HasOne("PortraMeta.Data.Entities.Actor", "Actor")
                        .WithMany("VideoActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortraMeta.Data.Entities.VideoFile", "VideoFile")
                        .WithMany("VideoActors")
                        .HasForeignKey("VideoFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("VideoFile");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.VideoFile", b =>
                {
                    b.HasOne("PortraMeta.Data.Entities.Library", "Library")
                        .WithMany("VideoFiles")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PortraMeta.Data.Entities.Studio", "Studio")
                        .WithMany("VideoFiles")
                        .HasForeignKey("StudioId");

                    b.Navigation("Library");

                    b.Navigation("Studio");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.Actor", b =>
                {
                    b.Navigation("VideoActors");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.Library", b =>
                {
                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.Studio", b =>
                {
                    b.Navigation("VideoFiles");
                });

            modelBuilder.Entity("PortraMeta.Data.Entities.VideoFile", b =>
                {
                    b.Navigation("VideoActors");
                });
#pragma warning restore 612, 618
        }
    }
}
